### ISSUE TITLE
*crash* *reload* *recrash* Rereload*... ect.

### ISSUE THREAD

**Issue by Link-Jon** [dan200/ComputerCraft#101]
... can you help me out a bit..???
 = print(" I’m getting a crash while loading up 1.8 with a itibity-mini modpack…. XD… brb.. *2 min later*
 “Code Chicken (“Core 1.8”), (“Lib 1.8”)"
 ok mod list…
 –CCL, CCC Simplecore api?… Archimedes ships plus, Computer Craft 1.76 (1.8,) Crazy ores, Ichunutil 5.5.0, movingworld-mc, NEI… *PANT* done!… “)
 ooohh and my though is something about that baked file… but when I take out computer craft “the version I’m using” it works! (aka less crashing)

Loading mc...*
CRASH*

—- Minecraft Crash Report —-

[color=#133376][u][b]WARNING: coremods are present:
 CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
 CCCDeobfPlugin (unknown)
 NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
 CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
 Contact their authors BEFORE contacting forge

// I bet Cylons wouldn’t have this problem.

Time: 4/7/16 10:29 AM
 Description: Initializing game

java.lang.RuntimeException: No base model or submodel provided for this MultiModel.Baked.
 at net.minecraftforge.client.model.MultiModel$Baked.(MultiModel.java:50)
 at net.minecraftforge.client.model.MultiModel.bake(MultiModel.java:196)
 at net.minecraftforge.client.model.ModelLoader$WeightedPartWrapper.bake(ModelLoader.java:462)
 at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:561)
 at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:135)
 at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29)
 at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:130)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:474)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
 at net.minecraft.client.main.Main.main(SourceFile:120)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
 —————————————————————————————

— Head —
 Stacktrace:
 at net.minecraftforge.client.model.MultiModel$Baked.(MultiModel.java:50)
 at net.minecraftforge.client.model.MultiModel.bake(MultiModel.java:196)
 at net.minecraftforge.client.model.ModelLoader$WeightedPartWrapper.bake(ModelLoader.java:462)
 at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:561)
 at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:135)
 at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29)
 at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:130)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:474)

— Initialization —
 Details:
 Stacktrace:
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
 at net.minecraft.client.main.Main.main(SourceFile:120)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

— System Details —
 Details:
 Minecraft Version: 1.8
 Operating System: Windows 8.1 (amd64) version 6.3
 Java Version: 1.7.0_55, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 136070808 bytes (129 MB) / 589299712 bytes (562 MB) up to 3817865216 bytes (3641 MB)
 JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1487 9 mods loaded, 9 mods active
 States: ‘U’ = Unloaded ‘L’ = Loaded ‘C’ = Constructed ‘H’ = Pre-initialized ‘I’ = Initialized ‘J’ = Post-initialized ‘A’ = Available ‘D’ = Disabled ‘E’ = Errored
 UCH mcp{9.05} [minecraft coder pack] (minecraft.jar)
 UCH FML{8.0.99.99} [forge mod loader] (forge-1.8-11.14.3.1487.jar)
 UCH Forge{11.14.3.1487} [minecraft forge] (forge-1.8-11.14.3.1487.jar)
 UCH CodeChickenCore{1.0.5.34} [codechicken core] (minecraft.jar)
 UCH NotEnoughItems{1.0.5.82} [not enough items] (NotEnoughItems-1.8-1.0.5.82-universal.jar)
 UCH simplecore{1.2.0} [simplecore api] ([1.8] SimpleCore API v1.2.0.jar)
 UCH ComputerCraft{1.76} [computercraft] (ComputerCraft1.76.jar)
 UCH simpleores{1.7.1} [simpleores 2] (Crazy-ores-1.8.jar)
 UCH iChunUtil{5.5.0} [ichunutil] (iChunUtil-5.5.0.jar)
 Loaded coremods (and transformers):
 CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
 codechicken.lib.asm.ClassHeirachyManager
 codechicken.lib.asm.RenderHookTransformer
 CCCDeobfPlugin (unknown)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
 codechicken.nei.asm.NEITransformer
 CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
 codechicken.core.asm.InterfaceDependancyTransformer
 codechicken.core.asm.TweakTransformer
 codechicken.core.asm.DelegatedTransformer
 codechicken.core.asm.DefaultImplementationTransformer
 GL info: ‘ Vendor: ‘ATI Technologies Inc.’ Version: ‘4.5.13399 Compatibility Profile Context 15.201.1151.0’ Renderer: ‘AMD Radeon HD 6310 Graphics’
 Launched Version: 1.8-Forge11.14.3.1487
 LWJGL: 2.9.1
 OpenGL: AMD Radeon HD 6310 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
 GL Caps: Using GL 1.3 multitexturing.
 Using GL 1.3 texture combiners.
 Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
 Shaders are available because OpenGL 2.1 is supported.
 VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
 Is Modded: Definitely; Client brand changed to ‘fml,forge’
 Type: Client (map_client.txt)
 Resource Packs: []
 Current Language: English (US)
 Profiler Position: N/A (disabled)
[/b][/u][/color]

**Comment by BombBloke** [comment]
That version of Forge is from June last year. What happens if you update it?

**Comment by dan200** [comment]
Yep. This is caused by old Forge. Upgrade it.

**Comment by Link-Jon** [comment]
Hmm.... I was hoping I didn't need to do anyhitng to forge.... brb.... this will take longer than 1 post!

**Comment by Link-Jon** [comment]
P.S. It workedddd!!!!!!!!!!!!!!!!!!!!!!!!!!!
