### ISSUE TITLE
[1.80pr0] Crash when starting turtle

### ISSUE THREAD

**Issue by Xerus2000** [dan200/ComputerCraft#122]
Ok I know I shouldnt report stuff for 1.10, but for when the time comes...
When a turtle tries to dig a Block in 1.10 this Error happens, looks like it has to do with the sound:
[crash-2016-06-28_16.29.26-server.txt](https://github.com/dan200/ComputerCraft/files/337254/crash-2016-06-28_16.29.26-server.txt)

**Comment by Selim042** [comment]
I wouldn't post anything yet as it may be fixed while the 1.9.4 version gets polished.

**Comment by basilfx** [comment]
Same problemen over here

```
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:713) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) ~[lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.SoundType.func_185845_c()Lnet/minecraft/util/SoundEvent;
        at dan200.computercraft.shared.turtle.upgrades.TurtleTool.dig(TurtleTool.java:285) ~[TurtleTool.class:?]
        at dan200.computercraft.shared.turtle.upgrades.TurtleTool.useTool(TurtleTool.java:126) ~[TurtleTool.class:?]
        at dan200.computercraft.shared.turtle.core.TurtleToolCommand.execute(TurtleToolCommand.java:36) ~[TurtleToolCommand.class:?]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:998) ~[TurtleBrain.class:?]
        at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:185) ~[TurtleBrain.class:?]
        at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:259) ~[TileTurtle.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1797) ~[aht.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) ~[lq.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by cri5ti** [comment]
Also in 1.10.2 / ComputerCraft{1.80pr0}
https://gist.github.com/cri5ti/24b006fb636bac2cb24008a06ff0cbf3

**Comment by dan200** [comment]
Fixed. Thanks squiddev!
