### ISSUE TITLE
Crash (just opened a computer)

### ISSUE THREAD

**Issue by Eufranio** [dan200/ComputerCraft#124]
```
`---- Minecraft Crash Report ----
// Don't do that.

Time: 03/07/16 00:27
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at dan200.computercraft.core.terminal.Terminal.writeToNBT(Terminal.java:314)
	at dan200.computercraft.shared.common.ServerTerminal.writeDescription(ServerTerminal.java:96)
	at dan200.computercraft.shared.peripheral.monitor.TileMonitor.writeDescription(TileMonitor.java:320)
	at dan200.computercraft.shared.common.TileGeneric.func_145844_m(TileGeneric.java:188)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:629)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:571)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:84)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
`
```
Full crash report: http://pastebin.com/NpqA6bGY

**Comment by dan200** [comment]
This crash is already fixed in the current version

**Comment by Eufranio** [comment]
1.7.10?

**Comment by dan200** [comment]
no, current
