### ISSUE TITLE
[1.80pr0] Server crash when turtle digs on a dedicated server

### ISSUE THREAD

**Issue by negamartin** [dan200/ComputerCraft#150]
Whenever a turtle digs it attempts to call a method in `net.minecraft.block.SoundType`, which is only present in the client, therefore it crashes only when running the server separately.

Crash log:
`
  java.lang.NoSuchMethodError: net.minecraft.block.SoundType.func_185845_c()Lnet/minecraft/util/SoundEvent;
	at dan200.computercraft.shared.turtle.upgrades.TurtleTool.dig(TurtleTool.java:285)
	at dan200.computercraft.shared.turtle.upgrades.TurtleTool.useTool(TurtleTool.java:126)
	at dan200.computercraft.shared.turtle.core.TurtleToolCommand.execute(TurtleToolCommand.java:36)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:998)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:185)
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_73660_a(TileTurtle.java:259)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
`

I have temporarily solved the problem by dissasembling/assemblying TurtleTool.class and skipping the erroneous method call.

**Comment by SquidDev** [comment]
Possibly the same as #122?

**Comment by negamartin** [comment]
Oh, I see. I looked around and found nothing. I guess I have to look harder next time.

**Comment by SquidDev** [comment]
Don't worry. I just remembered this issue being reported before 😄.
