### ISSUE TITLE
[1.76pr5] Forge won't launch with computercraft.

### ISSUE THREAD

**Issue by KittyCatCode** [dan200/ComputerCraft#61]
Using forge 1.8.8-11.15.0.1630-1.8.8, the latest forge, forge won't start when computercraft is present. 
Stacktrace:
Time: 12/15/15 6:32 AM
Description: Initializing game

java.lang.RuntimeException: No base model or submodel provided for this MultiModel.Baked.
	at net.minecraftforge.client.model.MultiModel$Baked.<init>(MultiModel.java:50)
	at net.minecraftforge.client.model.MultiModel.bake(MultiModel.java:196)
	at net.minecraftforge.client.model.ModelLoader$WeightedPartWrapper.bake(ModelLoader.java:462)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:561)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:135)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:474)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by dan200** [comment]
ComputerCraft 1.76 is for Minecraft 1.8, not Minecraft 1.8.8
