### ISSUE TITLE
Sanity checking

### ISSUE THREAD

**Issue by cblair91** [dan200/ComputerCraft#93]
If a computer is removed pre-load (for which ever reason), ComputerCraft doesn't sanity check to see if it's still a computer, and not been removed.

`java.lang.NullPointerException: Ticking block entity
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.getFamily(TileComputerBase.java:412)
    at dan200.computercraft.shared.computer.blocks.TileComputer.createComputer(TileComputer.java:110)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:427)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145845_h(TileComputerBase.java:201)
    at net.minecraft.world.World.func_72939_s(World.java:2513)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)A detailed walkthrough of the error, its code path and all known details is as follows:
----------------------------------------------------------------------------------------- Head --
Stacktrace:
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.getFamily(TileComputerBase.java:412)
    at dan200.computercraft.shared.computer.blocks.TileComputer.createComputer(TileComputer.java:110)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.createServerComputer(TileComputerBase.java:427)
    at dan200.computercraft.shared.computer.blocks.TileComputerBase.func_145845_h(TileComputerBase.java:201)-- Block entity being ticked --
Details:
    Name: computer // dan200.computercraft.shared.computer.blocks.TileComputer
    Block type: ID #54 (tile.chest // net.minecraft.block.BlockChest)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-157,57,-63), Chunk: (at 3,3,1 in -10,-4; contains blocks -160,0,-64 to -145,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Actual block type: ID #54 (tile.chest // net.minecraft.block.BlockChest)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2513)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityHumanNPC['§2§lKet §rMarket'/1263, l='world', x=-14.06, y=14.00, z=0.70](§2§lKet §rMarket at -14.056888530734533,14.0,0.6983400830705376)]
    Chunk stats: ServerChunkCache: 1201 Drop: 0
    Level seed: 1
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
    Level generator options:
    Level spawn location: World: (0,14,10), Chunk: (at 0,0,10 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 310600237 game time, 311870574 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 5173 (now: false), thunder time: 58150 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by dan200** [comment]
This bug was fixed a while ago, which version are you running?

**Comment by cblair91** [comment]
1.75
And is all computer load methods using sanity checking now, or just this one issue?

**Comment by dan200** [comment]
A lot of fixes were made between 1.75->1.76. If you can reproduce any
crashes in the current version, feel free to report them here. Closing this
one as solved
